import { firstName, formatDate } from '@shared/utils';

/**
 * DBL's regret letter, as the candidate will read it: addressed by first
 * name, naming the post, ending with the automated-email notice.
 *
 * A preview only: the server sends its own copy
 * (`HRM_Backend/src/modules/candidates/regret-mail.ts`), so a bundle that
 * drifted from it could never change what goes out. Keep the two in step.
 *
 * @param name the one candidate it is for; left out for a batch, where each
 *   is addressed by their own name and the preview says "[First name]".
 */
export function regretMailPreview(input: {
  name?: string | null;
  position?: string | null;
}): string {
  const greeting = input.name?.trim() ? firstName(input.name) : '[First name]';
  const position = input.position?.trim();
  const post = position
    ? ` for the position of ${position}${/[.!?]$/.test(position) ? '' : '.'}`
    : '.';
  return `Dear ${greeting},

Thank you for your interest in DBL Group and for the time and effort you invested in our recruitment process${post}

After careful consideration of your application and the requirements of the role, we have decided not to proceed with your candidature for this position.

We truly appreciate the opportunity to learn more about your experience, skills, and career aspirations. While we are unable to move forward with your application at this time, we encourage you to explore future opportunities with DBL Group that may be a strong match for your profile.

Explore Current Opportunities:
${window.location.origin}/careers

Where appropriate, your profile may also be considered for future opportunities aligned with your qualifications and experience.

At DBL Group, we are committed to a fair, transparent, inclusive, and merit-based recruitment process, ensuring every candidate is assessed objectively against the requirements of the role.

Thank you again for considering DBL Group as part of your career journey. We wish you continued success and growth in your professional endeavors.

Warm regards,
Talent Acquisition Team
DBL Group

This is an automated email generated by the DBL Group Recruitment System. Please do not reply to this email.`;
}

/** The server's batch cap — each one is a real email sent while you wait. */
export const MAX_REGRET_PER_SEND = 100;

/** Everything the modal needs to know about a candidate. */
export interface RegretTarget {
  id: string;
  name: string;
  email: string | null;
  stage: string;
  regretSentAt: string | null;
}

/**
 * Why this candidate cannot be sent the letter, or null when they can.
 * Mirrors `regretMailBlocker` on the server, which has the final say.
 */
export function regretBlocker(c: RegretTarget): string | null {
  if (c.stage.toLowerCase() !== 'rejected') return 'Not rejected';
  if (!c.email?.trim()) return 'No email on file';
  if (c.regretSentAt) return `Sent ${formatDate(c.regretSentAt)}`;
  return null;
}
